language: node_js

node_js:
  - "lts/*" # Latest LTS
  - "node" # Latest Stable

matrix:
  include:
    - # Linting stage
      node_js: "lts/*" # Latest LTS
      script: npm run lint

cache: npm

after_success: npm run coverage
